// See https://aka.ms/new-console-template for more information

using System.Collections.Concurrent;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using nfm_world_library;

var sb = new StringBuilder();
var types = new ConcurrentQueue<Type>();

sb.AppendLine($"// Auto-generated Rust FFI bindings for {nameof(BackendGameSparker)}");
sb.AppendLine("// Generated by NFMWorld.RustBindGen");
sb.AppendLine("// Do not edit this file directly");
sb.AppendLine();

foreach (var type in typeof(BackendGameSparker).Assembly.GetTypes())
{
    foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
    {
        if (method.GetCustomAttribute<UnmanagedCallersOnlyAttribute>() is not { } unmanagedCallersOnlyAttribute)
        {
            continue;
        }

        var name = unmanagedCallersOnlyAttribute.EntryPoint;
        var rustReturnType = MapCSharpTypeToRust(method.ReturnType) ?? $"/* Unsupported return type {method.ReturnType} */ std::ffi::c_void";
        var rustParamList = new List<string>();
        var rustCallingConvention = MapCSharpCallingConventionToRust(unmanagedCallersOnlyAttribute.CallConvs?[0] ?? typeof(CallConvCdecl))
                                    ?? "extern \"C\"";
        foreach (var param in method.GetParameters())
        {
            var rustParamType = MapCSharpTypeToRust(param.ParameterType) ?? $"/* Unsupported param type {param.ParameterType} */ std::ffi::c_void";
            rustParamList.Add($"{param.Name}: {rustParamType}");
        }

        sb.AppendLine($"unsafe {rustCallingConvention} {{");
        sb.AppendLine($"  pub fn {name}({string.Join(", ", rustParamList)}) -> {rustReturnType};");
        sb.AppendLine("}");
        sb.AppendLine();
    }
}

while (types.TryDequeue(out var type))
{
    sb.AppendLine($"#[repr(C)]");
    sb.AppendLine($"pub struct {type.Name} {{");
    foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
    {
        var rustFieldType = MapCSharpTypeToRust(field.FieldType) ?? $"/* Unsupported field type {field.FieldType} */ std::ffi::c_void";
        sb.AppendLine($"    pub {ToSnakeCase(field.Name)}: {rustFieldType},");
    }
    sb.AppendLine($"}}");
    sb.AppendLine();
}

Console.WriteLine(sb.ToString());

string? MapCSharpTypeToRust(Type type)
{
    if (type == typeof(void)) return "void";
    if (type == typeof(byte)) return "u8";
    if (type == typeof(sbyte)) return "i8";
    if (type == typeof(short)) return "i16";
    if (type == typeof(ushort)) return "u16";
    if (type == typeof(int)) return "i32";
    if (type == typeof(uint)) return "u32";
    if (type == typeof(long)) return "i64";
    if (type == typeof(ulong)) return "u64";
    if (type == typeof(float)) return "f32";
    if (type == typeof(double)) return "f64";
    if (type == typeof(bool)) return "bool";
    if (type == typeof(IntPtr)) return "*const std::ffi::c_void";
    if (type == typeof(UIntPtr)) return "*const std::ffi::c_void";
    if (type.IsPointer) return "*const " + MapCSharpTypeToRust(type.GetElementType()!);
    if (type.IsValueType)
    {
        if (type.GetCustomAttribute<InlineArrayAttribute>() is { } inlineArrayAttribute)
        {
            var elementType = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).First().FieldType;
            var rustElementType = MapCSharpTypeToRust(elementType) ?? $"/* Unsupported inline array element type {elementType} */ std::ffi::c_void";
            return $"[{rustElementType}; {inlineArrayAttribute.Length}]";
        }
        
        if (!types.Contains(type))
        {
            types.Enqueue(type);
        }
        return type.Name;
    }
    return null;
}

static string? MapCSharpCallingConventionToRust(Type type)
{
    if (type == typeof(CallConvCdecl)) return "extern \"C\"";
    if (type == typeof(CallConvStdcall)) return "extern \"system\"";
    if (type == typeof(CallConvThiscall)) return "extern \"thiscall\"";
    if (type == typeof(CallConvFastcall)) return "extern \"fastcall\"";
    return null;
}

static string ToSnakeCase(string typeName)
{
    var sb = new StringBuilder();
    for (int i = 0; i < typeName.Length; i++)
    {
        var c = typeName[i];
        if (char.IsUpper(c) && i > 0)
        {
            // Check if this is part of an abbreviation (next char is also uppercase or we're at the end)
            // But add underscore if previous char was lowercase or if next char is lowercase (end of abbreviation)
            var prevChar = typeName[i - 1];
            var isEndOfAbbreviation = i + 1 < typeName.Length && char.IsLower(typeName[i + 1]);
            
            if (char.IsLower(prevChar) || isEndOfAbbreviation)
            {
                sb.Append('_');
            }
        }
        sb.Append(char.ToLower(c));
    }
    return sb.ToString();
}